@extends('layout.master')
@section('title', 'Privacy Policy - American Life Insurance')
@section('css')
<link rel="stylesheet" href="{{ asset('asset/css/style2.css')}}">
@endsection
@section('content')
<div class="container content-container">
    <h2 class="ppolicy2">American Life Coverage Privacy Policy</h2>
    <div>
        <span style="color: rgb(7, 31, 43); font-family: Lato, sans-serif; font-size: 16px; letter-spacing: normal; background-color: rgb(249, 249, 249);">Effective 6/1/2022</span><br>
        <span style="color: rgb(7, 31, 43); font-family: Lato, sans-serif; font-size: 16px; letter-spacing: normal; background-color: rgb(249, 249, 249);">Updated 6/10/2022</span><br>
    </div>
    <h5 class="ppolicy2">Please read this Privacy Policy carefully before using this website.</h5>
    <p class="ppolicy2">Thank you for visiting our website, owned and operated by American Life Coverage (“<span style="letter-spacing: -0.27px;">American Life Coverage</span>”, “we”, “us”, “our”). “<span style="letter-spacing: -0.27px;">American Life Coverage</span>”, “we”, “us”, and “our” for purposes of this Privacy Policy refers only to&nbsp;<span style="letter-spacing: -0.27px;">American Life Coverage</span>I and its subsidiaries, and to not our parent company Prudential Financial or any of its other subsidiaries.&nbsp;<span style="letter-spacing: -0.27px;">American Life Coverage&nbsp;</span>is here to protect and improve the personal and financial health of all consumers. Before you use this website and our other services—which include, among other things, collecting information from you in order to generate insurance and other financial product quotes and to connect you with insurance agents and other financial services professionals to discuss your needs (our website and these and other services are referred to collectively as the “Services”)—we’d like to tell you more about the information we collect about you and what we do with it.</p>
    <p class="ppolicy2">When you use, access or interact with our services (for example, by inputting your information on this website), you are agreeing to our&nbsp;<a class="op" href="{{ route('terms')}}">Terms of Service</a>&nbsp;and also consenting to how we collect, share and otherwise use information about you as described in this Privacy Policy.</p>
    <p class="ppolicy2"><strong>California Resident?</strong>&nbsp; But before jumping in, if you are a California resident, please review our California Consumer Privacy Act Disclosure and California Privacy Notice at Collection located in our&nbsp;<a class="op" href="{{ route('privacy_center')}}">Privacy Center</a>.</p>
    <p class="ppolicy2">We care about your privacy and have drafted this policy to be as easy-to-read as possible. Please read it and feel free to reach out with any questions using the contact methods provided below.</p>
    <h4 class="ppolicy2">A.&nbsp;<u>What This Policy Covers</u></h4>
    <p class="ppolicy2">This Privacy Policy covers how we collect, use, and share information in connection with your access and use of our Services. It does not cover the privacy practices of third parties that we do not own or control, nor of our parent company Prudential Financial or its other subsidiaries.</p>
    <p class="ppolicy2">That said, you should know that we may provide third party content or links to third-party websites or applications (for example, links to websites of&nbsp;<span style="letter-spacing: -0.27px;">American Life Coverage&nbsp;</span>companies we partner with if you request to view a quote). When you leave our Services or interact with a third-party feature, you should also read the applicable third party’s privacy policies and terms of service to make sure you understand how they might collect and share information about you.</p>
    <h4 class="ppolicy2">B.&nbsp;<u>What Information We Collect</u></h4>
    <p class="ppolicy2">There are three primary ways we collect information about you: (1) when you give it to us, (2) through automated technologies, and (3) by asking others for it. We’ve broken down each of those three categories in further detail below.</p>
    <h4 class="ppolicy2">1. Information You Provide to Us</h4>
    <p class="ppolicy2">You may provide information to us in various ways, such as through online forms, over the phone, or via other means offered through our Services. The most likely way you’ll provide us with information about yourself is by entering it in our websites in order to have us generate a quote or other offers for you. Please note that we collect, retain, and use such information, as well as the information in categories 2 and 3 below, even if you do not complete the web flow. For example, we may ask you some basic questions about your medical history in order to generate a life insurance quote for you. The types of information you provide us fit into two categories. &nbsp;<em><strong>Personal Information</strong></em>&nbsp;is information that identifies you personally, such as your name, address, email address, Social Security number or phone number.&nbsp;<em><strong>Non-Personal Information</strong></em>&nbsp;is information about you or your household that, on its own, doesn’t identify you personally, like your gender, income or what types of products you’re interested in.</p>
    <p class="ppolicy2">When we combine information that isn’t Personal Information (like Usage Information, as explained below) with Personal Information, we treat it like Personal Information for as long as it is combined.</p>
    <h4 class="ppolicy2">2. Information We Automatically Collect</h4>
    <p class="ppolicy2">Second, we automatically collect from your device or computer certain information about how you access and interact with our Services. We call this &nbsp;<em><strong>Usage Information</strong></em>&nbsp; for purposes of this Privacy Policy. Usage Information is a critical part of how we improve your experience on our websites and, more importantly, provide you with more personalized insights and recommendations, which is the core of what we aim to do at&nbsp;<span style="letter-spacing: -0.27px;">American Life Coverage</span>. We may use various technologies to collect and store Usage Information in connection your use of our Services. These may include things like cookies, browser storage, web beacons, and other tracking technologies. There are four types of Usage Information we may collect:</p>
    <ul class="ppolicy2">
        <li><strong>Device Information</strong>. We collect information about your device, such as your operating system, hardware model, application or browser type and version, and unique identifiers associated with your device.</li>
        <li><strong>Log Information</strong>. We automatically collect certain information in system logs or similar files about how you interact with our Services, such as which buttons you click on. This Log Information may also include things like your IP address, browser or device configuration, date and time of access and cookie information.</li>
        <li><strong>Information Used to Reidentify</strong>. We collect information in order to reidentify you across multiple browsing sessions and devices (for instance, connecting your current browsing with a prior session in which you provided us your name).</li>
        <li><strong>Location Information</strong>. We may use certain information like your IP address or other Device Information or Log Information to estimate your location. We may also request to use location-enabled services on your device (which typically provide GPS or Wi-Fi access point details) to enhance our Services.</li>
    </ul>
    <p class="ppolicy2">We, or other parties we do business with, may place or recognize unique cookies or other technologies on your browser when you visit our Services to collect information about your use of the Services and your other online activities over time and across different websites and apps, and may use that information to serve interest-based advertisements to you as you browse the Internet. To learn more about interest-based advertising, please review the information below:</p>
    <ul class="ppolicy2">
        <li>To opt-out of such collection and use for online behavioral advertising by the Digital Advertising Alliance (DAA) participating companies in the United States, please visit:&nbsp;<a class="op" href="http://www.aboutads.info/choices/" target="_blank" rel="noopener">DAA Choices</a>&nbsp;and&nbsp;<a class="op" href="http://www.aboutads.info/appchoices/" target="_blank" rel="noopener">DAA AppChoices</a>.</li>
        <li>To opt-out from the use of information about your online activities for online behavioral advertising by NAI member companies, visit:&nbsp;<a class="op" href="https://www.networkadvertising.org/choices/" target="_blank" rel="noopener">NAI</a>. Please note that even if you opt-out, you may still receive advertisements that are not customized based on your usage Information.</li>
    </ul>
    <p class="ppolicy2">Note that you may choose to set your web browser to refuse cookies, or to alert you when cookies are being sent. On your mobile device, you may also adjust your privacy and advertising settings to control whether you want to receive more relevant advertising. If you do make such changes, please note that some parts of our Services may not function properly.</p>
    <h4 class="ppolicy2">3. Information Third Parties Provide to Us About You</h4>
    <p class="ppolicy2">To provide you with more personalized product recommendations, we collect information about you from third parties and from other sources, such as publicly available databases, providers of demographic information, fraud prevention services, and social media platforms. For example, we may collect information from a third party to verify the address you provided, to help us understand your occupational background, or to confirm you are not a bot or entering fraudulent information.</p>
    <p class="ppolicy2">We need to collect personal information to provide Services to you. If you do not provide the information requested, we may not be able to provide the Services. If you disclose any personal information relating to other people to us or to our partners in connection with our provision of Services, you represent that you have the authority to do so and to permit us to use the information in accordance with this Privacy Policy.</p>
    <h4 class="ppolicy2">C.&nbsp;<u>How We Use the Information We Collect</u></h4>
    <p class="ppolicy2">We use the information we collect from you and third parties to operate our Services, including to provide you with insurance quotes, communicate with you, and improve your experience. These are a few examples of how we use the information we collect:</p>
    <ul class="ppolicy2">
        <li><strong>To provide personalized services to you</strong>. We use the information we collect to provide the Services to you in a personalized way. Financial services products are complex and we therefore do not take a one-size-fits-all approach to helping you find the right products. The information we collect enables us to do this by giving us a more detailed picture of who you are.</li>
        <li><strong>To improve our Services</strong>. We are constantly trying to improve our Services. The information we collect also helps us improve the experience we provide to consumers and the way we match consumers to product recommendations in real time. For example, in some instances, we may use information you have provided, even if you have not completed the web flow, so that if you return to the website this information will be pre-loaded for your convenience.</li>
        <li><strong>To prevent fraud or malicious activities</strong>. We may also use the information you provide to detect, deter, prevent, or take action regarding incidents such as suspected fraud, malicious or illegal activities, or violations of our policies.</li>
        <li><strong>To communicate with you</strong>. Part of providing personalized services is quickly connecting you with real people who can help walk you through your financial services options. Therefore, we use the information you provide to contact you about the quotes or other product recommendations you requested through our websites. For example, if you provide your phone number and email and then consent to being contacted by us, we will likely call you to connect you with one of our agents. We may also text and email you information about how to contact us, specific offers, and other information pertinent to your financial services inquiry.
            <ul>
                <li><strong>Opting Out of Further Communication</strong>. While we aim to make it as easy as possible for you to talk directly with an expert, we will honor your request not to be contacted further. You can easily opt-out of further communications from us by requesting to be placed on our Do Not Call list, by replying “STOP” to our text messages, by using our Communication Opt-Out form found&nbsp;<a class="op" href="{{ route('opt_out')}}">here</a>, or by unsubscribing from our email list.</li>
            </ul>
        </li>
        <li><strong>For legal reasons</strong>. We operate in a regulated industry and therefore reserve the right to access, use, preserve, transfer or disclose, at any time without notice to you, any information related to your use of our Services as reasonably necessary to do any of the following: comply with applicable law; respond to complaints, legal actions or governmental requests; enforce our Terms of Service; or respond to other similar matters. We may also use third-party services to record your actions on this website to help meet our compliance and legal obligations.</li>
    </ul>
    <h4 class="ppolicy2">D.&nbsp;<u>When We Share or Sell the Information We Collect</u></h4>
    <p class="ppolicy2">As a distributor of financial services products, we work with a number of partners to deliver the Services and therefore share information with those partners. Also, although we aim to directly meet all of our customers’ needs, we also—with your express permission—may sell the information you provide us to third parties, to help give you more options and better meet your needs. The following is a list of how we share and/or sell your information, including Personal Information, in connection with your use of our Services:</p>
    <ul class="ppolicy2">
        <li><strong>Share information with our partners (e.g., insurance carriers) to provide and improve our Services</strong>. We may share information about you with the third-party partners we collaborate with to provide you the Services you requested. For example, we work closely with certain insurance carriers to provide our customers with personalized insurance quotes. When you request a quote, we may therefore share your information with the carriers to generate the quote for you. Or we may call you and redirect your call directly to agents of one of those carriers to walk you through your options. Or we may redirect you to the website of one of those partners and pre-populate your information there to help seamlessly satisfy your financial services inquiry.</li>
        <li><strong>Share information with service providers acting on our behalf</strong>. We may share information about you with service providers we use to have them perform on our behalf any of the activities we are permitted to conduct under this Privacy Policy and our Terms of Service. For example, we may share your information with our third party data-provider partners to enable them to provide us with further information about you, so that we can further personalize your experience and product recommendations. We also may share your information with our service providers in helping us ensure compliance with our legal obligations and requirements, including so that we have a documented record of your consent to be contacted by us or by third-party providers. We also may share with third parties deidentified or aggregated data that we collect, such as deidentified demographic information, or information about the computer or device from which you access the Service. We share such information for a variety of purposes, including to monitor and understand Service usage, and improve our own products and features.</li>
        <li><strong>Sell information to third-party providers with your permission</strong>. After obtaining your permission, we may sell your information to third parties who will also try to meet your needs. These third parties may be other insurance agencies, insurance carriers, financial services providers, or other entities that facilitate the process of connecting customers with financial services providers. These third parties, or the entities they work with, may contact you based on the consent you have provided.</li>
        <li><strong>As Part of a Corporate Change</strong>. We may disclose and transfer information about you to a third party as part of, or in preparation for, a change of control, restructuring, corporate change, or sale or transfer of assets.</li>
        <li><strong>For Legal Reasons</strong>. We reserve the right to transfer or disclose information about you to third parties for certain legal purposes as described above.</li>
    </ul>
    <h4 class="ppolicy2">E.&nbsp;<u>How We Protect Your Information</u></h4>
    <p class="ppolicy2">We seek to use reasonable administrative, technical and physical safeguards, and other security measures to protect personal information within our organization from growing threats. Unfortunately, no data transmission over the Internet or data storage system can be guaranteed to be 100% secure. If you have reason to believe that your interaction with us is no longer secure, please immediately notify us in accordance with the contact methods provided below.</p>
    <h4 class="ppolicy2">F.&nbsp;<u>Miscellaneous</u></h4>
    <p class="ppolicy2"><strong>Effective date of this Privacy Policy</strong>. This Privacy Policy is effective as of July 1, 2020. We reserve the right to change this Privacy Policy at any time. We will note within the Privacy Policy when it was last updated. Any changes to this Privacy Policy will be effective as of the day they are posted. Use of our Services following these changes signifies acceptance of the revised Privacy Policy.</p>
    <p class="ppolicy2"><strong>California Residents</strong>. As mentioned at the beginning of this Privacy Policy, please note that if you are a California resident, we have an additional privacy disclosure applicable to you in our&nbsp;<a class="op" href="{{ route('privacy_center')}}">Privacy Center</a>.</p>
    <p class="ppolicy2"><strong>Want More Information?</strong>&nbsp; We appreciate you taking the time to read this. If you have questions regarding this policy or privacy practices at&nbsp;<span style="letter-spacing: -0.27px;">American Life Coverage&nbsp;</span>, you can email us at&nbsp;<a class="op" href="mailto:support@americanlifeinsurance.com">support@americalifeinsurance.com</a>&nbsp;Legal.&nbsp;</p>
    <h4 class="ppolicy2"><u>Contact Us</u></h4>
    <p class="ppolicy2">
        <span style="font-weight: 700; letter-spacing: -0.27px;">Wirte us :</span>
        <span style="font-family: var( --e-global-typography-text-font-family ), Sans-serif; font-size: 18px; letter-spacing: -0.27px;"><br>
            113 Cherry St, Seattle,<br>WA, 98104-2205,<br>
        United States of America.</span>
    </p>
    <p class="ppolicy2"><span style="font-weight: 700; letter-spacing: -0.27px;">Customer Service :</span><span style="font-family: var( --e-global-typography-text-font-family ), Sans-serif; font-size: 18px; letter-spacing: -0.27px;"><br></span><a class="op" href="tel:(833) 625-0148/" style="font-size: 16px; letter-spacing: -0.27px;">(833) 625 0148</a><br>
    </p>
</div>
@endsection